### ISSUE TITLE
Question, Blfim - Tool how to batch processing dds 2 fblim？

### ISSUE THREAD

**Issue by fejich** [aboood40091/BFLIM-Tool#1]
Open the bflim folder can bulk export dds file, how to inject back？

I would like to translate the game into Chinese, need to edit more than one such bflim file.

**Comment by fejich** [comment]
Forgive me bad English, I use google translation to write this post

**Comment by aboood40091** [comment]
If you want to inject back, you have to open each BFLIM individually and not open a folder.

**Comment by fejich** [comment]
I mean batch inject back
Thank you for the reply

**Comment by aboood40091** [comment]
If you mean replacing multiple BFLIMs at the same time, it isn't possible yet.
